// lib/BentoGrid/BentoGrid.react.tsx
/** @jsxImportSource react */

import classNames from 'classnames'
import type { CSSProperties } from 'react'
import { CBentoGridProps } from './BentoGrid.common'
import styles from './BentoGrid.module.css'

export interface BentoGridProps extends CBentoGridProps {  
  className?: string
  style?: CSSProperties
}


export const BentoGrid = ({
  className,
  ...props
}: BentoGridProps) => {


  return (
  <div> </div>
 
  )
}

// lib/BentoGrid/BentoGrid.qwik.tsx
/** @jsxImportSource @builder.io/qwik */

import {
  CSSProperties,
  ClassList,
  Slot,
  component$
} from '@builder.io/qwik'
import { CBentoGridProps, } from './BentoGrid.common'
import styles from './BentoGrid.module.css'

export interface BentoGridProps extends CBentoGridProps {  
  class?: ClassList
  style?: CSSProperties
}

export const BentoGrid = component$(
  ({ ...props }: BentoGridProps) => {


    return (
      <div 
        style={props.style}  
        class={[
          props.class,
          styles.bentoGrid,  
        ]}
      >
        <Slot></Slot>
      </div>
    )
  },
)
