// lib/Resizable/Resizable.react.tsx
/** @jsxImportSource react */

import { CSSProperties, ReactNode, useEffect, useRef, useState } from 'react'
import styles from './Resizable.module.css'
import classnames from 'classnames'
import { CResizableProps } from './Resizable.common'

type ResizeType = 'Y' | 'X' | 'XY'

export interface ResizableProps extends CResizableProps {
  class?: string
  style?: CSSProperties
  
  onSizeChange?: (size: { width: number; height: number }) => void
  children?: ReactNode
}

export function Resizable(props: ResizableProps) {
  const [resizeType, setResizeType] = useState<ResizeType | undefined>()
  const ref = useRef<HTMLDivElement | null>(null)

  const handleMouse = (event: React.MouseEvent<HTMLElement> | MouseEvent) => {
    if (event.type === 'mousedown') {
      if (props.disabled || (props['disabledX'] && props['disabledY'])) return
      if (props['disabledX']) setResizeType('Y')
      else if (props['disabledY']) setResizeType('X')
      else setResizeType('XY')
    } else if (event.type === 'mouseup' || event.type === 'mouseleave') {
      setResizeType(undefined)
    } else if (event.type === 'mousemove' && ref.current && resizeType) {
      const root = ref.current
      let { left, top } = root.getBoundingClientRect()

      if (resizeType.includes('X')) {
        root.style.width = event.clientX - left + 'px'
      }
      if (resizeType.includes('Y')) {
        root.style.height = event.clientY - top + 'px'
      }
      if (props.onSizeChange) {
        let { width, height } = root.getBoundingClientRect()
        props.onSizeChange({ width, height })
      }
    }
  }

  useEffect(() => {
    if (resizeType) {
      document.addEventListener('mouseup', handleMouse)
      document.addEventListener('mouseleave', handleMouse)
      document.addEventListener('mousemove', handleMouse)
      document.body.classList.add(styles['onDrag' + resizeType])
      return () => {
        document.removeEventListener('mouseup', handleMouse)
        document.removeEventListener('mouseleave', handleMouse)
        document.removeEventListener('mousemove', handleMouse)
        document.body.classList.remove(styles['onDrag' + resizeType])
      }
    }
  }, [resizeType])

  return (
    <div
      ref={ref}
      className={classnames([props.class, styles.root])}
      style={props.style}
    >
      {props.children}
      {!props['disabledX'] && !props.disabled && (
        <div
          className={classnames([
            styles.dragBorderX,
            resizeType && styles['onDrag' + resizeType],
          ])}
          onMouseDown={handleMouse}
        ></div>
      )}
      {!props['disabledY'] && !props.disabled && (
        <div
          className={classnames([
            styles.dragBorderY,
            resizeType && styles['onDrag' + resizeType],
          ])}
          onMouseDown={handleMouse}
        ></div>
      )}
    </div>
  )
}

// lib/Resizable/Resizable.qwik.tsx
/** @jsxImportSource @builder.io/qwik */

import {
  $,
  CSSProperties,
  ClassList,
  PropFunction,
  Slot,
  component$,
  useSignal,
  useTask$,
} from '@builder.io/qwik'
import { CResizableProps } from './Resizable.common'
import styles from './Resizable.module.css'

type ResizeType = 'Y' | 'X' | 'XY'

export interface ResizableProps extends CResizableProps {
  class?: ClassList
  style?: CSSProperties
  onSizeChange$?: PropFunction<
    (size: { width: number; height: number }) => void
  >
}

export const Resizable = component$((props: ResizableProps) => {
  const resizeTypeSig = useSignal<ResizeType>()
  const ref = useSignal<HTMLElement>()

  const handleMouse = $((event: MouseEvent) => {
    if (event.type === 'mousedown') {
      if (props.disabled || (props.disabledX && props.disabledY)) return
      if (props.disabledX) resizeTypeSig.value = 'Y'
      else if (props.disabledY) resizeTypeSig.value = 'X'
      else resizeTypeSig.value = 'XY'
    } else if (event.type === 'mouseup' || event.type === 'mouseleave') {
      resizeTypeSig.value = undefined
    } else if (event.type === 'mousemove' && ref.value && resizeTypeSig.value) {
      const root = ref.value
      let { left, top } = root.getBoundingClientRect()

      if (resizeTypeSig.value.includes('X')) {
        root.style.width = event.clientX - left + 'px'
      }
      if (resizeTypeSig.value.includes('Y')) {
        root.style.height = event.clientY - top + 'px'
      }
      if (props.onSizeChange$) {
        let { width, height } = root.getBoundingClientRect()
        props.onSizeChange$({ width, height })
      }
    }
  })

  useTask$(({ track, cleanup }) => {
    const resizeType = track(() => resizeTypeSig.value)
    if (resizeType) {
      document.addEventListener('mouseup', handleMouse)
      document.addEventListener('mouseleave', handleMouse)
      document.addEventListener('mousemove', handleMouse)
      document.body.classList.add(styles['onDrag' + resizeType])
      cleanup(() => {
        document.removeEventListener('mouseup', handleMouse)
        document.removeEventListener('mouseleave', handleMouse)
        document.removeEventListener('mousemove', handleMouse)
        document.body.classList.remove(styles['onDrag' + resizeType])
      })
    }
  })

  return (
    <div ref={ref} class={[props.class, styles.root]} style={props.style}>
      <Slot />
      {!props.disabledX && !props.disabled && (
        <div
          class={[
            styles.dragBorderX,
            resizeTypeSig.value && styles['onDrag' + resizeTypeSig.value],
          ]}
          onMouseDown$={handleMouse}
        ></div>
      )}
      {!props.disabledY && !props.disabled && (
        <div
          class={[
            styles.dragBorderY,
            resizeTypeSig.value && styles['onDrag' + resizeTypeSig.value],
          ]}
          onMouseDown$={handleMouse}
        ></div>
      )}
    </div>
  )
})
