// lib/CounterDown/CounterDown.qwik.tsx
/** @jsxImportSource @builder.io/qwik */

import {
  CSSProperties,
  ClassList,
  Slot,
  component$
} from '@builder.io/qwik'
import { colorFlagsOptions } from '../Theme/ColorFlags'
import { selectedFlag } from '../Theme/selectedFlag'
import { CCounterDownProps } from './CounterDown.common'
import styles from './CounterDown.module.css'

export interface CounterDownProps extends CCounterDownProps {
  class?: ClassList
  style?: CSSProperties
  open?: boolean
  shadow?: boolean
  showIcon?: boolean
  name?: string
}

export const CounterDown = component$(
  ({ color, open, shadow, showIcon, name, ...props }: CounterDownProps) => {

    const themeColor = selectedFlag(props, colorFlagsOptions)

    let opened = open ?? false

    let hasShadow = shadow ?? false

    let isIcon = showIcon ?? true

    return (
     <div></div>
    )
  },
)

// lib/CounterDown/CounterDown.react.tsx
/** @jsxImportSource react */

import type { CSSProperties, ReactNode } from 'react'
import { CCounterDownProps } from './CounterDown.common'
import styles from './Accordion.module.css'

export interface CounterDownReactProps extends CCounterDownProps {
  style?: CSSProperties
  children?: ReactNode
  className?: string
  title: string
  open?: boolean
  showIcon?: boolean
  shadow?: boolean
  name?: string
}

export function CounterDown({
  title,
  className,
  shadow,
  showIcon,
  name,
  ...props
}: CounterDownReactProps) {
  const opened = props.open ?? false
  let hasShadow = shadow ?? false

  let isIcon = showIcon ?? true

  return (
   <div></div>
  )
}
